### ISSUE TITLE
Connect.java does not match output of Connect_C.m

### ISSUE THREAD

**Issue by Ezana1994** [aahamed/SeniorDesign#1]
Given input:
 p = (-524, 382);
 q = (-585, 502);

MATLAB code returns pointer value of 1. Java file returns pointer value of 0.

I will look into this later, but this is an issue we should sort out ASAP as other files depend on this.

**Comment by aahamed** [comment]
Output for this test case should now match. Test Cases for Connect can be found in [test/TestConnect.java](https://github.com/aahamed/SeniorDesign/blob/in_progress/test/TestConnect.java)

To run the test:
- make testConnect
- make runTestConnect

It will run all tests in TestConnect.java and display any errors if there are any.

**Comment by aahamed** [comment]
The error was that my pq_vector was declared as:
int[] pq_vector = new int[2];
while it should have been: 
double[] pq_vector = new double[2];

As a result it was doing integer division instead of floating point division.
