### ISSUE TITLE
Distance_matrix.java

### ISSUE THREAD

**Issue by aahamed** [aahamed/SeniorDesign#10]
Can you add support for taking in List<Coordinate<Integers>> in Distance_matrix?

For example:

```
public static List<List<Integers>> distanceMatrix(List<Coordinate<Integers>> coords)
{
       ... compute distance matrix
       return dMatrix;
}
```

Here coords is the coordinates of the initial clusters and distance matrix is of type ArrayList<List<Integer>> and contains the distance between every pair of coordinates. This method would be very helpful for testing InitMax.java. Actually, I can go ahead and add the enhancement myself if you are not going to be working on this file.

**Comment by josuegaleas** [comment]
DistanceMatrix was modified to have this behavior in the latest beta release. Moreover, it returns a DMout object, which contains the distance matrix and other information.
