### ISSUE TITLE
FindAN

### ISSUE THREAD

**Issue by Ezana1994** [aahamed/SeniorDesign#7]
This issue may be related to the one thats already being worked on right now.

Input
I = [143,-795]
J = 0
K = [147,-754]
Ind = [-1,0,-1]

FindAN.java Output:
Result = [[-329.0], [-789.0]]
Flag = 1;

FindAN2.m Output:
Result = [130,-769]
Flag = 1;

**Comment by aahamed** [comment]
Fixed this testcase. You can view this testcase and more in [test/TestFindAN.java](https://github.com/aahamed/SeniorDesign/blob/aadil/test/TestFindAN.java)

Problem was in case 12 I was doing:
`double[][] b_ji = {{0.5 * I.getX() + I.getY()},{ -0.5 * K.getX() + (0.5*K.getY())}};`
but it should have been:
`double[][] b_ji = {{I.getX() + 0.5*I.getY()},{ -0.5 * K.getX() + (0.5*K.getY())}};`

Here is the [commit](https://github.com/aahamed/SeniorDesign/commit/45cc300ee171a5a0bb7d8d005c68cac63c6e0157)
